### ISSUE TITLE
Table in two schemas error

### ISSUE THREAD

**Issue by mdecima** [loresoft/EntityFrameworkCore.Generator#144]
I have this database structure

CREATE TABLE [dbo].[TableCompany](
	[IdCompany] [int] NOT NULL,
	[CompanyName] [nchar](10) NULL,
 CONSTRAINT [PK_TableCompany] PRIMARY KEY CLUSTERED 
(
	[IdCompany] ASC
)) ON [PRIMARY]

 GO

CREATE TABLE [Schema1].[TableCompany](
	[IdCompany] [int] NOT NULL,
	[CompanyName] [nchar](10) NULL,
 CONSTRAINT [PK_TableCompany] PRIMARY KEY CLUSTERED 
(
	[IdCompany] ASC
)) ON [PRIMARY]

GO

And that is my configuration file
database:
  tables:
    - TableCompany
  schemas:
    - dbo

The program **generate 2 entities** TableCompany and TableCompany1. One for each schema.
I expected the generation of just only one entity for the schema dbo.

**Comment by pwelter34** [comment]
There are a couple ways to handle this.  First is to only include the dbo schema.

```yaml
database:
  connectionString: ...
  schemas:
    - dbo
```

Next would be to include the schema in the entity name.

```yaml
data:
  entity:
    name: '{Table.Schema}{Table.Name}'
```

Last would be to exclude the table 

```yaml
database:
  exclude:
    - exact: 'Schema1.TableCompany'
```

hope that helps

~ Paul
